name: CI
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint && pnpm run build
